
spring:
  application:
    name: spring-kafka-demo
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        schema.registry.url: http://localhost:8082
    producer:
      acks: all

server:
  port: 8080

logging:
  level:
    root: info
    org.org.apache.kafka: trace
